#MSVC configuration
spring.application.name=msvc-Configurations
server.port=8005

# SpringDoc configurations
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/apidoc/swagger-ui.html
springdoc.api-docs.path=/apidoc/

# BD configuration using R2DBC (para SQL Server)
spring.r2dbc.url=r2dbc:sqlserver://172.22.224.1:1433;databaseName=EGM;instanceName=SQLSERVER;encrypt=true;trustServerCertificate=true
spring.r2dbc.username=apiexport
spring.r2dbc.password=Osm3d1c4

# Configuración de Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Modo Debug
debug=false
