#MSVC configuration
spring.application.name=msvc-Configurations
server.port=8005

# SpringDoc configurations
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/apidoc/swagger-ui.html
springdoc.api-docs.path=/apidoc/
springdoc.show-actuator=true

# Configuración de la base de datos usando R2DBC para SQL Server
spring.r2dbc.master.url=r2dbc:mssql://172.22.224.1:1433/master?instanceName=SQLSERVER&encrypt=true&trustServerCertificate=true
spring.r2dbc.egm.url=r2dbc:mssql://172.22.224.1:1433/EGM?instanceName=SQLSERVER&encrypt=true&trustServerCertificate=true
spring.r2dbc.username=apiexport
spring.r2dbc.password=Osm3d1c4

# Modo Debug
debug=false

#Actuator
management.server.port=9090
management.endpoints.web.exposure.include=*


